version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    # build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test1:3:1,test2:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 41943040
      KAFKA_MESSAGE_MAX_BYTES: 41943040
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 41943040
      KAFKA_MAX_REQUEST_SIZE: 41943040
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /Users/lsd/workspace/kafka:/home